# Defines the configuration version.
# The only possible value is "2".
version: "2"

# Options for analysis running.
run:
  # Timeout for total work, e.g. 30s, 5m, 5m30s.
  # Default: 0 (disabled)
  timeout: 5m

  # Include test files or not.
  # Default: true
  tests: true

  # The mode used to evaluate relative paths.
  # Default: cfg
  relative-path-mode: gomod

# Linters configuration.
linters:
  # Default set of linters.
  # The value can be:
  # - `standard`: https://golangci-lint.run/usage/linters/#enabled-by-default
  # - `all`: enables all linters by default.
  # - `none`: disables all linters by default.
  # - `fast`: enables only linters considered as "fast".
  # Default: standard
  default: none

  # Enable specific linters.
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - copyloopvar # replaces exportloopref in newer versions
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # All available settings of specific linters.
  settings:
    dupl:
      # Tokens count to trigger issue.
      # Default: 150
      threshold: 100

    funlen:
      # Checks the number of lines in a function.
      # Default: 60
      lines: 100
      # Checks the number of statements in a function.
      # Default: 40
      statements: 50

    goconst:
      # Minimal length of string constant.
      # Default: 3
      min-len: 2
      # Minimum occurrences of constant string count to trigger issue.
      # Default: 3
      min-occurrences: 2

    gocyclo:
      # Minimal code complexity to report.
      # Default: 30 (but we recommend 10-20)
      min-complexity: 15

    lll:
      # Max line length, lines longer will be reported.
      # Default: 120
      line-length: 140

    misspell:
      # Correct spellings using locale preferences for US or UK.
      # Default is to use a neutral variety of English.
      locale: US

    revive:
      # Sets the default severity.
      # Default: warning
      severity: warning

  # Exclusion rules
  exclusions:
    rules:
      # Exclude gochecknoinits from cmd/ files (required for cobra)
      - path: cmd/
        linters:
          - gochecknoinits

      # Exclude gochecknoinits from utils (required for initialization)
      - path: internal/utils/utils.go
        linters:
          - gochecknoinits

      # Exclude high cyclomatic complexity for complex functions
      - path: cmd/generate.go
        linters:
          - gocyclo

      - path: internal/config/loader.go
        linters:
          - gocyclo

      - path: internal/plist/generator.go
        linters:
          - gocyclo

      # Exclude gosec subprocess warnings for legitimate use cases
      - path: cmd/edit.go
        linters:
          - gosec
        text: "G204:"

      - path: cmd/tail.go
        linters:
          - gosec
        text: "G204:"

      # Exclude gosec file inclusion warnings for config/plist operations
      - path: cmd/generate.go
        linters:
          - gosec
        text: "G304:"

      - path: internal/utils/utils.go
        linters:
          - gosec
        text: "G304:"

      # Exclude line length warnings for struct tags
      - path: internal/config/schema.go
        linters:
          - lll

      # Exclude some linters from test files
      - path: _test\.go
        linters:
          - funlen
          - dupl

      # Exclude funlen for complex but necessary functions
      - path: cmd/generate.go
        linters:
          - funlen

      - path: internal/plist/generator.go
        linters:
          - funlen

      # Exclude gosec file path warnings for logs command (legitimate use)
      - path: cmd/logs.go
        linters:
          - gosec
        text: "G304:"

# Formatters configuration.
formatters:
  # Enable specific formatters.
  enable:
    - gofmt
    - goimports

  # Formatters settings.
  settings:
    goimports:
      # A list of prefixes, which, if set, checks import paths
      # with the given prefixes are grouped after 3rd-party packages.
      # Default: []
      local-prefixes:
        - github.com/mjmorales/rcon-mcp-server

# Issues configuration.
issues:
  # Maximum issues count per one linter.
  # Default: 50
  max-issues-per-linter: 0

  # Maximum count of issues with the same text.
  # Default: 3
  max-same-issues: 0
